### ISSUE TITLE
Sticky notes not editable in Safari

### ISSUE THREAD

**Issue by vitorio** [gauravchl/stickyboard#2]
Hello, in Safari, the default CSS properties for contenteditable means the sticky notes can't be edited in Safari.

See e.g. https://stackoverflow.com/questions/20435166/contenteditable-not-working-in-safari-but-works-in-chrome

Adding the CSS in the accepted answer to e.g. css/scafolding.import.styl makes the notes work in Safari.

**Comment by gauravchl** [comment]
@vitorio Thanks for pointing it. CSS Updated.
It's very old project, never thought someone would use it.
